### ISSUE TITLE
getspeller.php  rejects  JSimth@lol.com but accepts jsmith@lol.com

### ISSUE THREAD

**Issue by ebobtron** [ebobtron/Speller-BigBoard#50]
is this the culprit.  This dog belongs to you.  Any ideas about a fix

**$regex = "/^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,3})$/";**

we should pass upper and lower case local part without prejudice.

**Comment by ebobtron** [comment]
http://en.wikipedia.org/wiki/Email_address#Local_part

**Comment by theB264** [comment]
In general, using a regex to verify an email address is an excerise in futility.  This is a good one `$regex = "/@/";`

**Comment by ebobtron** [comment]
Sent response from my phone already, not here yet I guess.  So here goes repeato boy.

This is the kind of help that is not.  
The question is B, is this a suitable fix for capital letter used in the local part of the address.

     $regex = "/^[_A-Za-z0-9-]+(\.[_A-Za-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,3})$/";

I added the A-Z thingy to the local part in front of the little @ thingy.

**Comment by theB264** [comment]
What I mean is that with email addresses and `regex`s is that, you either don't check them or you check them halfway, or, ideally, you send a confirmation code to be returned to you.  There are always going to be valid addresses that your regex will flag as invalid.  I'm not joking when I suggest `/@/`.  There are standards `http://tools.ietf.org/html/rfc5322#section-3.4` and it's claimed impossible to write a regex to match them due to recursion and/or catastrophic backtracking. That's why if you search for an email regex you get one of every flavour.  See `http://davidcel.is/blog/2012/09/06/stop-validating-email-addresses-with-regex/`

**Comment by ebobtron** [comment]
See, that's the kind of answer that is.   Thank you.

**Comment by ebobtron** [comment]
some new information is available, thanks B

https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address

**Comment by theB264** [comment]
:-)

**Comment by ebobtron** [comment]
we can close this: used the recommended regex in the above website
```php
    // new one suggested by theB264  see issue#50 github
    $regex = "/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9]".
             "(?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9]".
             "(?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/";
```
Thanks you Brain again.
